dependencies:
  phone_numbers_parser: ^8.2.1
  dlibphonenumber: ^1.1.9
  flutter_libphonenumber: ^2.2.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
    sdk: flutter

  file_picker: ^4.6.1
  csv: ^4.0.4

  cupertino_icons: ^1.0.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.7+1
  avatar_glow: ^1.2.0
  cached_network_image: ^3.2.0
  csv: ^4.2.1
  json_serializable: ^4.5.0
  path_provider: ^2.0.11
  flutter_contacts: ^2.0.3
  call_log: ^0.6.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable_generator: ^4.5.0
dependencies:
  json_annotation: ^4.5.0
dependencies:
  floor: ^1.4.3
dependencies:
  flutter_secure_storage: ^4.2.0
dependencies:
  android_intent: ^0.6.0
  rxdart: ^0.27.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  material_icons: ^1.0.0
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.0.0
firebase_remote_config: ^4.0.0
dependencies:
  flutter:
    sdk: flutter
  media_query: ^1.0.0
