dependencies:
  phone_numbers_parser: ^8.2.1
  dlibphonenumber: ^1.1.9
  flutter_libphonenumber: ^2.2.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
    sdk: flutter

  file_picker: ^4.6.1
  csv: ^4.0.4


